visualization:
  flip_x: false
  flip_y: false

pipelines:
  mean_pca_bestkmeans:
    imputer:
      name: SimpleImputer
      strategy: mean

    reducer:
      name: PCA
      n_components: 2

    scaler:
      name: NoOpScaler

    clusterer:
      name: BestKMeans
      k_bounds: [2, 5]

  mean_pacmap_kmeans:
    imputer:
      name: SimpleImputer
      strategy: mean

    reducer:
      name: PaCMAP
      n_components: 2
      n_neighbors: null

    scaler:
      name: NoOpScaler

    clusterer:
      name: KMeans
      n_clusters: 5

  mean_pacmap_hdbscanflat:
    imputer:
      name: SimpleImputer
      strategy: mean

    reducer:
      name: PaCMAP
      n_components: 2
      n_neighbors: null

    scaler:
      name: NoOpScaler

    clusterer:
      name: HDBSCANFlat
      n_clusters: 8
      min_cluster_size: 20

  mean_localmap_hdbscanflat:
    imputer:
      name: SimpleImputer
      strategy: mean

    reducer:
      name: LocalMAP
      n_components: 2
      n_neighbors: null

    scaler:
      name: NoOpScaler

    clusterer:
      name: HDBSCANFlat
      n_clusters: 8
      min_cluster_size: 20

  mean_localmap_besthdbscanflat:
    imputer:
      name: SimpleImputer
      strategy: mean

    reducer:
      name: LocalMAP
      n_components: 2
      n_neighbors: null

    scaler:
      name: NoOpScaler

    clusterer:
      name: BestHDBSCANFlat
      k_bounds: [2, 8]
      min_cluster_size: 20
      cluster_selection_method: "leaf"

  mean_localmap_bestkmeans:
    imputer:
      name: SimpleImputer
      strategy: mean

    reducer:
      name: LocalMAP
      n_components: 2
      n_neighbors: null

    scaler:
      name: NoOpScaler

    clusterer:
      name: BestKMeans
      k_bounds: [2, 10]

  knn5d_pacmap_besthdbscanflat:
    imputer:
      name: KNNImputer
      n_neighbors: 5
      weights: distance

    reducer:
      name: PaCMAP
      n_components: 2
      n_neighbors: null

    scaler:
      name: NoOpScaler

    clusterer:
      name: BestHDBSCANFlat
      k_bounds: [2, 10]

  knn5d_pacmap_kmeans: &knn_pacmap_kmeans
    imputer:
      name: KNNImputer
      n_neighbors: 5
      weights: distance

    reducer: &pacmap_reducer
      name: PaCMAP
      n_components: 2
      n_neighbors: null

    scaler:
      name: NoOpScaler

    clusterer:
      name: KMeans
      n_clusters: 5

  knn5d_localmap_kmeans:
    <<: *knn_pacmap_kmeans
    reducer:
      <<: *pacmap_reducer
      name: LocalMAP
