pipelines:
  polis_classic:
    imputer:
      name: SimpleImputer
      strategy: mean

    reducer:
      name: PCA
      n_components: 2

    scaler:
      name: NoOpScaler

    clusterer:
      name: KMeans
      n_clusters: 5

    visualization:
      flip_x: false
      flip_y: false

  mean_pacmap_kmeans:
    imputer:
      name: SimpleImputer
      strategy: mean

    reducer:
      name: PaCMAP
      n_components: 2
      n_neighbors: null

    scaler:
      name: NoOpScaler

    clusterer:
      name: KMeans
      n_clusters: 5

    visualization:
      flip_x: false
      flip_y: false

  knn_pacmap_kmeans: &knn_pacmap_kmeans
    imputer:
      name: KNNImputer
      n_neighbors: 5
      weights: distance

    reducer: &pacmap_reducer
      name: PaCMAP
      n_components: 2
      n_neighbors: null

    scaler:
      name: NoOpScaler

    clusterer:
      name: KMeans
      n_clusters: 5

    visualization:
      flip_x: false
      flip_y: false

  knn_localmap_kmeans:
    <<: *knn_pacmap_kmeans
    reducer:
      <<: *pacmap_reducer
      name: LocalMAP

    visualization:
      flip_x: false
      flip_y: false
