pipelines:
  polis_classic:
    imputer:
      name: SimpleImputer
      strategy: mean

    reducer:
      name: PCA
      n_components: 2

    scaler:
      name: NoOpScaler

    clusterer:
      name: KMeans
      n_clusters: 5

  knn_pacmap_kmeans:
    imputer:
      name: KNNImputer
      n_neighbors: 5
      weights: distance

    reducer:
      name: PaCMAP
      n_components: 2
      n_neighbors: null

    scaler:
      name: NoOpScaler

    clusterer:
      name: KMeans
      n_clusters: 5
